### ISSUE TITLE
Installing a package doesn't work [Windows]

### ISSUE THREAD

**Issue by ispasmihai** [GDGVIT/pip-gui#13]
I use 32bit python 2.7  with pip 18.1 on a 64bit Windows 10.

I installed pip-gui 1.1 with pip. 

The package search works as expected however the installation does not work at all: first of all no feedback is provided in the Progress Window. No information/warning/error printed in the console. The progress does nothing and can stay forever in this state. After the continue button is pressed the 'installation' exists with a success message(_'Selected Packages have been installed'_) even though it actually didn't install the package. The uninstall package list do contain the "installed" package but it doesn't appear in my python environment.

The uninstall functionality behaves similar. The package is not actually uninstall from my python environment and no feedback provided in the Progress Window.

Note: I did try to use the application in **virtualenv** and it seems that the install/uninstall features work as expected. The package is installed/uninstalled to/from my virtual Python environment. However, I cannot use virtualenv in my completed project so this does not represent a solution for me.

**Comment by L04DB4L4NC3R** [comment]
Issue resolved in #21
