### ISSUE TITLE
Update README for application installation

### ISSUE THREAD

**Issue by ispasmihai** [GDGVIT/pip-gui#14]
For me at least, the installation is confusing. I did install pip-gui.exe using pip(18.1) and used the directory structure that I cloned from here. I used it because just installing pip-gui.exe is not enough: the application needs some relative files which do not exist. The application cannot create the needed files. 
However what I noticed in the cloned project is that there is a `setup.py` which has `build` and `install `command.  The help command gives more information but still not helping too much (_'will build package underneath build/'_, _'will install the package'_) - it is referring to the installation of a python package or the installation of pip-gui itself? Either way at `python setup.py install` step  I get the following error: 

> Searching for PyQt5
> Reading https://pypi.python.org/simple/PyQt5/
> No local packages or working download links found for PyQt5
> error: Could not find suitable distribution for Requirement.parse('PyQt5')

Maybe the incorrect installation determines the issues explained at #13

**Comment by L04DB4L4NC3R** [comment]
Readme has been updated in #16
