### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Jalkhov** [GDGVIT/pip-gui#33]
Error when press Next in **Install new packages**, **Update existing packages** and **Uninstall existing packages.**

`FileNotFoundError: [Errno 2] No such file or directory: 'c:\\pythons\\python39-64\\lib\\site-packages\\pipgui\\.\\Resource_Files\\Installed Packages\\installedPackageList3.json'`

**Comment by BRO3886** [comment]
Hey, thanks for reporting the issue! I'll check what's going wrong.

**Comment by Jalkhov** [comment]
I have fixed this problem in my pull request #34 I have modified the way the paths of certain files are obtained, now absolute paths are used to avoid problems with relative paths.

**Comment by Cyberavater** [comment]
Log:
```
  File "c:\python39\lib\site-packages\pipgui\__main__.py", line 184, in radioCheck
    self.update = UpdateWindow()
  File "c:\python39\lib\site-packages\pipgui\__main__.py", line 221, in __init__
    self.outdatedPackages = json.load(open(
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\python39\\lib\\site-packages\\pipgui\\.\\Resource_Files\\Outdated Packages\\outdatedPackageList3.json'
```

**Comment by teckscam** [comment]
Hi. I just installed and started.

![pipgui-log](https://user-images.githubusercontent.com/86368444/124024728-82cbd000-d9e7-11eb-9ab3-ae5ac417b270.jpg)

**Comment by teckscam** [comment]
Hi. I just installed and started.

![pipgui-log](https://user-images.githubusercontent.com/86368444/124024728-82cbd000-d9e7-11eb-9ab3-ae5ac417b270.jpg)

looking the code this directories not exist at installation directory

INSTALLED_DIR = './Resource_Files/Installed Packages/'
OUTDATED_DIR = './Resource_Files/Outdated Packages/'
ASSETS_DIR = './Resource_Files/Assets/'
PACKAGE_DIR = './Resource_Files/Current Packages/'

**Comment by teckscam** [comment]
Hi. I just installed and started.

![pipgui-log](https://user-images.githubusercontent.com/86368444/124024728-82cbd000-d9e7-11eb-9ab3-ae5ac417b270.jpg)

looking the code this directories not exist at installation directory

INSTALLED_DIR = './Resource_Files/Installed Packages/'
OUTDATED_DIR = './Resource_Files/Outdated Packages/'
ASSETS_DIR = './Resource_Files/Assets/'
PACKAGE_DIR = './Resource_Files/Current Packages/'

**Comment by teckscam** [comment]
Hi. I just installed and started.

![pipgui-log](https://user-images.githubusercontent.com/86368444/124024728-82cbd000-d9e7-11eb-9ab3-ae5ac417b270.jpg)

looking the code this directories not exist in the installation directory

INSTALLED_DIR = './Resource_Files/Installed Packages/'
OUTDATED_DIR = './Resource_Files/Outdated Packages/'
ASSETS_DIR = './Resource_Files/Assets/'
PACKAGE_DIR = './Resource_Files/Current Packages/'

**Comment by teckscam** [comment]
I´m create a pull requests. This bug stay on the setup file.
https://github.com/GDGVIT/pip-gui/pull/36#issue-681355656

**Comment by teckscam** [comment]
I grouped everything and added some corrections.
Pull requests -> corrections and optimizations, fix this error included. #37

**Comment by Anton-V-K** [comment]
This issue still happens with Python 3.10 on Windows 10 64-bit.
```
...>pipgui.exe
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\pipgui\__main__.py", line 188, in radioCheck
    self.uninstall = UninstallWindow()
  File "C:\Program Files\Python310\lib\site-packages\pipgui\__main__.py", line 291, in __init__
    self.allPackages = json.load(open(
FileNotFoundError: [Errno 2] No such file or directory:
   'C:\\Program Files\\Python310\\lib\\site-packages\\pipgui\\.\\Resource_Files\\Installed Packages\\installedPackageList3.json'
```
It doesn't matter what mode is selected - the error is always the same.
`pipgui-1.4` was installed via `pip install pipgui`.
