### ISSUE TITLE
Use pyqt5

### ISSUE THREAD

**Issue by r00tdaemon** [GDGVIT/pip-gui#8]
Use pyqt5 for a simple reason that its wheels are available on pypi so users don't have to go through the pain of installing pyqt4 themselves.

**Comment by necrose99** [comment]
https://www.kdab.com/automated-porting-from-qt-4-to-qt-5/

Gentoo Linux , (https://www.youtube.com/watch?v=6l6vqPUM_FE)  QT4 going going gone.... being distro droped

**Comment by zdenop** [comment]
PR #11 should this

**Comment by Geek-ubaid** [comment]
This issue is solved in #11
