### ISSUE TITLE
Add *.ui files

### ISSUE THREAD

**Issue by r00tdaemon** [GDGVIT/pip-gui#9]
Add the *.ui (qtdesigner) files in /UI folder so that it's easier for contributors to make GUI changes.

**Comment by L04DB4L4NC3R** [comment]
@ayushpriya10 UI files can be added in the release, rather than the main repo.

**Comment by ayushpriya10** [comment]
Sure. That works fine for me. Do you want me to push a release with the UI files? @L04DB4L4NC3R

**Comment by L04DB4L4NC3R** [comment]
> Sure. That works fine for me. Do you want me to push a release with the UI files? @L04DB4L4NC3R

Yes. Mark this release as `v1.1`. All odd releases will be used for testing and even releases will be stable. For now, we can make a v1.1 to check the github action. v1.2 can be made when #13 is resolved

**Comment by ayushpriya10** [comment]
> > Sure. That works fine for me. Do you want me to push a release with the UI files? @L04DB4L4NC3R
> 
> Yes. Mark this release as `v1.1`. All odd releases will be used for testing and even releases will be stable. For now, we can make a v1.1 to check the github action. v1.2 can be made when #13 is resolved

Okay, I'll add a directory with all the *.ui files and push v1.1

**Comment by ayushpriya10** [comment]
I've pushed the required files and made a release.

**Comment by r00tdaemon** [comment]
I know this is late but fwiw, UI files should have been in the repo instead of the release as the main purpose is to make it easier to contribute to the project (for someone who wants to contribute to GUI fixes using the qt designer instead of modifying the auto generated files). On the other hand, these file shouldn't be of any use to end users so including them in release doesn't make sense.
